# git-cliff configuration file (https://git-cliff.org/docs/configuration)

[changelog]
# Template to be rendered for each release. (https://keats.github.io/tera/docs/#introduction)
body = """
{% for group, commits in commits | group_by(attribute="group") %}
    ### {{ group | striptags | trim | upper_first }}
    {% for commit in commits %}
        - {% if commit.scope %}{{ commit.scope | upper_first }}: {% endif %}\
            {% if commit.breaking %}[**breaking**] {% endif %}\
            {{ commit.message | upper_first }}\
    {% endfor %}
{% endfor %}
"""

[git]
tag_pattern = "^[0-9]+\\.[0-9]+\\.[0-9]+$"

[bump]
initial_tag = "1.0.0"
