exclude = [
    'https://test.tld/tag-manager',         # Path used to mock matomo in unit tests
    'https://familienportal.de/resource',   # Base path for assets hosted on familienportal
    'https?://localhost',                   # Path is sometimes used in comments
]
