name: CI

on: push

permissions:
  contents: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  lint-and-test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/cached-node-install

      - name: lint and test
        run: npm run test-all

  e2e-test:
    uses: ./.github/workflows/e2e-test.yml

  build:
    runs-on: ubuntu-24.04
    outputs:
      artifact_name: assets
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/cached-node-install

      - name: build assets
        run: npm run build
        env:
          EGR_BUILD_VERSION_HASH: ${{ github.sha }}

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: ./dist
          name: assets

  deploy:
    needs:
      - lint-and-test
      - e2e-test
      - build
    uses: ./.github/workflows/deploy-to-github-pages.yml
    with:
      path: main
      artifact_name: ${{ needs.build.outputs.artifact_name }}
    secrets: inherit

  generate-sbom:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: generate bill
        uses: advanced-security/generate-sbom-action@v1 # trusted as part of GitHub organization
        id: generate-sbom

      - name: upload bill as artifact
        uses: actions/upload-artifact@v4.3.2
        with:
          path: ${{ steps.generate-sbom.outputs.fileName }}
          name: SBOM

  audit-licenses:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/cached-node-install

      - name: Audit Licenses
        run: npm run audit-licenses
