name: CI

on: push

permissions:
  contents: write
  id-token: write

defaults:
  run:
    shell: bash

jobs:
  static-code-analysis:
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/cached-node-install

      - name: lint
        run: npm run type-check && npm run lint && npm run stylelint

  test-suite-vitest:
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/cached-node-install

      - name: test
        run: npm run test

  test-suite-playwright:
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/cached-node-install

      - uses: ./.github/actions/cached-playwright-setup

      - name: Run playwright e2e tests
        run: npm run test-e2e
        env:
          PLAYWRIGHT_TEST_IGNORE: "tests/cases/smokeTest.spec.ts"

      - name: Upload playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 1

  deploy:
    needs:
      - static-code-analysis
      - test-suite-vitest
      - test-suite-playwright
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/github-pages-deploy.yml
    with:
      path: /main
    secrets: inherit

  generate-sbom:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: generate bill
        uses: advanced-security/generate-sbom-action@v1 # trusted as part of GitHub organization
        id: generate-sbom

      - name: upload bill as artifact
        uses: actions/upload-artifact@v4.3.2
        with:
          path: ${{ steps.generate-sbom.outputs.fileName }}
          name: SBOM

  audit-licenses:
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/cached-node-install

      - name: Audit Licenses
        run: npm run audit-licenses

  original-rechner-lock:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - run: |
          git diff-tree --name-only -r ${{ github.sha }} \
            | grep 'original-rechner/src' && exit 1 || exit 0
