name: CI

on: push

permissions:
  contents: write
  id-token: write

defaults:
  run:
    shell: bash

jobs:
  lint-and-test:
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/cached-node-install

      - name: lint and test
        run: npm run test-all

  e2e-test:
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/cached-node-install

      - uses: ./.github/actions/cached-playwright-setup

      - name: Run Playwright e2e tests
        run: npm run test-e2e
        env:
          PLAYWRIGHT_TEST_IGNORE: "tests/cases/smokeTest.spec.ts"

      - name: Upload Playwright blob report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 1

  deploy:
    needs:
      - lint-and-test
      - e2e-test
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy-to-github-pages.yml
    with:
      path: /main
    secrets: inherit

  generate-sbom:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: generate bill
        uses: advanced-security/generate-sbom-action@v1 # trusted as part of GitHub organization
        id: generate-sbom

      - name: upload bill as artifact
        uses: actions/upload-artifact@v4.3.2
        with:
          path: ${{ steps.generate-sbom.outputs.fileName }}
          name: SBOM

  audit-licenses:
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/cached-node-install

      - name: Audit Licenses
        run: npm run audit-licenses

  verify-original-rechner-remains-untouched:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - run: |
          git diff-tree --name-only -r ${{ github.sha }} \
            | grep 'original-rechner/src' && exit 1 || exit 0
