name: Metrics (Matomo to Metabase) Synchronization

on:
  schedule:
    - cron: "55 23 * * *"

jobs:
  run-metrics:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js (LTS)
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        working-directory: metrics-sync
        run: npm install

      - name: Run metrics sync script
        working-directory: metrics-sync
        run: npm run sync -- $(date +'%Y-%m-%d')
        env:
          EGR_METRICS_SYNC_MATOMO_AUTHENTICATION_TOKEN: ${{ secrets.EGR_METRICS_SYNC_MATOMO_AUTHENTICATION_TOKEN }}
          EGR_METRICS_SYNC_MATOMO_DOMAIN: ${{ secrets.EGR_METRICS_SYNC_MATOMO_DOMAIN }}
          EGR_METRICS_SYNC_NOCO_AUTHENTICATION_TOKEN: ${{ secrets.EGR_METRICS_SYNC_NOCO_AUTHENTICATION_TOKEN }}
          EGR_METRICS_SYNC_NOCO_DOMAIN: ${{ secrets.EGR_METRICS_SYNC_NOCO_DOMAIN }}
          EGR_METRICS_SYNC_NOCO_PORT: ${{ secrets.EGR_METRICS_SYNC_NOCO_PORT }}
