name: Sync to OpenCoDE

concurrency: sync

on:
  push:
    branches: [main]

jobs:
  sync_to_opencode:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Ensure all branches are available
        run: |
          git fetch origin -u '+refs/heads/*:refs/heads/*' --update-head-ok

      - name: Sync repo to OpenCoDE
        shell: bash
        run: |
          set -x

          # Create ssh client config
          mkdir ~/.ssh
          cat <<EOF > ~/.ssh/config
          Host $DESTINATION_HOST
            ServerAliveInterval 60
            ServerAliveCountMax 5
            KexAlgorithms ecdh-sha2-nistp521
          EOF

          # Add host key
          ssh-keyscan $DESTINATION_HOST > ~/.ssh/known_hosts

          # Start ssh-agent and add private key
          eval $(ssh-agent)
          echo "$SSH_KEY" | sed '$ s/\n$//' | ssh-add -

          # Push main branch
          git remote add destination git@$DESTINATION_HOST:$DESTINATION_REPO
          git push --force --prune destination main:main
          git push --force --tags destination
        env:
          SSH_KEY: ${{ secrets.OPENCODE_SSH_PRIVATE_KEY }}
          DESTINATION_HOST: gitlab.opencode.de
          DESTINATION_REPO: digitalservicebund/elterngeldrechner.git
